# GitHub Sponsors configuration
# Remove or comment out the platforms you don't want to use

# github: [username]
# patreon: username
# open_collective: ona-platform
# ko_fi: username
# custom: ["https://www.paypal.me/username"]
